#!/usr/bin/env python3
'''Script to transcode a disc using HandBrake'''

import os
import subprocess
import sys

# ripped with:
#makemkvcon --decrypt backup --progress=-same disc:0 disc

def transcode(out, options):
    '''Call HandBrakeCLI with specified options.'''
    if os.path.isfile(out):
        print(f'File {out} exists, skipping')
    else:
        cmd = ['HandBrakeCLI',
               '--preset', 'AV1 MKV 2160p60 4K',
               '--output', f'{out}']
        cmd.extend(options)
        subprocess.run(cmd, check=True)

work_dir = '/mnt/raid/media/tv/Bluey'
src_dirs = [f'{work_dir}/rip/s1d1',
            f'{work_dir}/rip/s1d2',
            f'{work_dir}/rip/s2d1',
            f'{work_dir}/rip/s2d2',
            f'{work_dir}/rip/s3d1',
            f'{work_dir}/rip/s3d2']

for src_dir in src_dirs:
    scan_file = f'{src_dir}.scan'
    if not os.path.exists(scan_file):
        print('Scanning...')
        with open(scan_file, 'w', encoding='utf8') as scan:
            subprocess.run(['HandBrakeCLI',
                            '-i', src_dir,
                            '--scan',
                            '--title', '0'],
                            stdout=scan,
                            stderr=subprocess.STDOUT, check=True)
    

os.makedirs(f'{work_dir}/Season 1', exist_ok=True)
src_dir = src_dirs[0]

# 1: all episodes
# 2: FBI warning
transcode(f'{work_dir}/Season 1/s1e05 - Shadowlands.mkv',
          ['--input', f'{src_dir}',
           '--title', '4',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e06 - The Weekend.mkv',
          ['--input', f'{src_dir}',
           '--title', '5',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e07 - BBQ.mkv',
          ['--input', f'{src_dir}',
           '--title', '6',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e02 - Hospital.mkv',
          ['--input', f'{src_dir}',
           '--title', '7',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e03 - Keepy Uppy.mkv',
          ['--input', f'{src_dir}',
           '--title', '8',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e01 - Magic Xylophone.mkv',
          ['--input', f'{src_dir}',
           '--title', '9',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e04 - Daddy Robot.mkv',
          ['--input', f'{src_dir}',
           '--title', '10',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e08 - Fruitbat.mkv',
          ['--input', f'{src_dir}',
           '--title', '11',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e09 - Horsey Ride.mkv',
          ['--input', f'{src_dir}',
           '--title', '12',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e10 - Hotel.mkv',
          ['--input', f'{src_dir}',
           '--title', '13',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e11 - Bike.mkv',
          ['--input', f'{src_dir}',
           '--title', '14',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e12 - Bob Bilby.mkv',
          ['--input', f'{src_dir}',
           '--title', '15',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e13 - Spygame.mkv',
          ['--input', f'{src_dir}',
           '--title', '16',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e14 - Takeaway.mkv',
          ['--input', f'{src_dir}',
           '--title', '17',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e15 - Butterflies.mkv',
          ['--input', f'{src_dir}',
           '--title', '18',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e16 - Yoga Ball.mkv',
          ['--input', f'{src_dir}',
           '--title', '19',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e17 - Calypso.mkv',
          ['--input', f'{src_dir}',
           '--title', '20',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e18 - The Doctor.mkv',
          ['--input', f'{src_dir}',
           '--title', '21',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e19 - The Claw.mkv',
          ['--input', f'{src_dir}',
           '--title', '22',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e20 - Markets.mkv',
          ['--input', f'{src_dir}',
           '--title', '23',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e21 - Blue Mountains.mkv',
          ['--input', f'{src_dir}',
           '--title', '24',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e22 - The Pool.mkv',
          ['--input', f'{src_dir}',
           '--title', '25',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e23 - Shops.mkv',
          ['--input', f'{src_dir}',
           '--title', '26',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e24 - Wagon Ride.mkv',
          ['--input', f'{src_dir}',
           '--title', '27',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e25 - Taxi.mkv',
          ['--input', f'{src_dir}',
           '--title', '28',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e26 - The Beach.mkv',
          ['--input', f'{src_dir}',
           '--title', '29',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
# 30: same as 26
# 31: all episodes

src_dir = src_dirs[1]
# 1: all episodes
# 2: FBI warning
transcode(f'{work_dir}/Season 1/s1e31 - Work.mkv',
          ['--input', f'{src_dir}',
           '--title', '4',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e32 - Bumpy and the Wise Old Wolfhound.mkv',
          ['--input', f'{src_dir}',
           '--title', '5',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e33 - Trampoline.mkv',
          ['--input', f'{src_dir}',
           '--title', '6',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e28 - Grannies.mkv',
          ['--input', f'{src_dir}',
           '--title', '7',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e29 - The Creek.mkv',
          ['--input', f'{src_dir}',
           '--title', '8',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e27 - Pirates.mkv',
          ['--input', f'{src_dir}',
           '--title', '9',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e30 - Fairies.mkv',
          ['--input', f'{src_dir}',
           '--title', '10',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e34 - The Dump.mkv',
          ['--input', f'{src_dir}',
           '--title', '11',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e35 - Zoo.mkv',
          ['--input', f'{src_dir}',
           '--title', '12',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e36 - Backpackers.mkv',
          ['--input', f'{src_dir}',
           '--title', '13',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e37 - The Adventure.mkv',
          ['--input', f'{src_dir}',
           '--title', '14',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e38 - Copycat.mkv',
          ['--input', f'{src_dir}',
           '--title', '15',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e39 - The Sleepover.mkv',
          ['--input', f'{src_dir}',
           '--title', '16',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e40 - Early Baby.mkv',
          ['--input', f'{src_dir}',
           '--title', '17',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e41 - Mums and Dads.mkv',
          ['--input', f'{src_dir}',
           '--title', '18',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e42 - Hide and Seek.mkv',
          ['--input', f'{src_dir}',
           '--title', '19',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e43 - Camping.mkv',
          ['--input', f'{src_dir}',
           '--title', '20',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e44 - Mount Mumandad.mkv',
          ['--input', f'{src_dir}',
           '--title', '21',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e45 - Kids.mkv',
          ['--input', f'{src_dir}',
           '--title', '22',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e46 - Chickenrat.mkv',
          ['--input', f'{src_dir}',
           '--title', '23',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e47 - Neighbours.mkv',
          ['--input', f'{src_dir}',
           '--title', '24',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e48 - Teasing.mkv',
          ['--input', f'{src_dir}',
           '--title', '25',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e49 - Asparagus.mkv',
          ['--input', f'{src_dir}',
           '--title', '26',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e50 - Shaun.mkv',
          ['--input', f'{src_dir}',
           '--title', '27',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e51 - Daddy Putdown.mkv',
          ['--input', f'{src_dir}',
           '--title', '28',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 1/s1e52 - Verandah Santa.mkv',
          ['--input', f'{src_dir}',
           '--title', '29',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
# 30: same as 28
# 31: all episodes

os.makedirs(f'{work_dir}/Season 2', exist_ok=True)
os.makedirs(f'{work_dir}/Season 2/extras', exist_ok=True)
src_dir = src_dirs[2]
# 1: all episodes
# 2: FBI warning
transcode(f'{work_dir}/Season 2/s2e05 - Hairdressers.mkv',
          ['--input', f'{src_dir}',
           '--title', '4',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e06 - Stumpfest.mkv',
          ['--input', f'{src_dir}',
           '--title', '5',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e07 - Favourite Thing.mkv',
          ['--input', f'{src_dir}',
           '--title', '6',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e02 - Hammerbarn.mkv',
          ['--input', f'{src_dir}',
           '--title', '7',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e03 - Featherwand.mkv',
          ['--input', f'{src_dir}',
           '--title', '8',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e01 - Dance Mode.mkv',
          ['--input', f'{src_dir}',
           '--title', '9',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e04 - Squash.mkv',
          ['--input', f'{src_dir}',
           '--title', '10',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e08 - Daddy Dropoff.mkv',
          ['--input', f'{src_dir}',
           '--title', '11',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e09 - Bingo.mkv',
          ['--input', f'{src_dir}',
           '--title', '12',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e10 - Rug Island.mkv',
          ['--input', f'{src_dir}',
           '--title', '13',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e11 - Charades.mkv',
          ['--input', f'{src_dir}',
           '--title', '14',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e12 - Sticky gecko.mkv',
          ['--input', f'{src_dir}',
           '--title', '15',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e13 - Dad Baby.mkv',
          ['--input', f'{src_dir}',
           '--title', '16',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e14 - Mum School.mkv',
          ['--input', f'{src_dir}',
           '--title', '17',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e15 - Trains.mkv',
          ['--input', f'{src_dir}',
           '--title', '18',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e16 - Army.mkv',
          ['--input', f'{src_dir}',
           '--title', '19',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e17 - Fancy Restaurant.mkv',
          ['--input', f'{src_dir}',
           '--title', '20',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e18 - Piggyback.mkv',
          ['--input', f'{src_dir}',
           '--title', '21',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e19 - The Show.mkv',
          ['--input', f'{src_dir}',
           '--title', '22',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e20 - Ticklecrabs.mkv',
          ['--input', f'{src_dir}',
           '--title', '23',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e21 - Escape.mkv',
          ['--input', f'{src_dir}',
           '--title', '24',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e22 - Bus.mkv',
          ['--input', f'{src_dir}',
           '--title', '25',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e23 - Queens.mkv',
          ['--input', f'{src_dir}',
           '--title', '26',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e24 - Flat Pack.mkv',
          ['--input', f'{src_dir}',
           '--title', '27',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e25 - Helicopter.mkv',
          ['--input', f'{src_dir}',
           '--title', '28',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/extras/Highball.mkv',
          ['--input', f'{src_dir}',
           '--title', '29',
           '--audio', '1,2',
           '--aname', 'English',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/extras/Green Bottles.mkv',
          ['--input', f'{src_dir}',
           '--title', '30',
           '--audio', '1',
           '--aname', 'English',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/extras/Archaeology.mkv',
          ['--input', f'{src_dir}',
           '--title', '31',
           '--audio', '1',
           '--aname', 'English',
           '--subtitle', '1',
           '--subname', 'English'])

src_dir = src_dirs[3]
# 1: all episodes
# 2: FBI warning
transcode(f'{work_dir}/Season 2/s2e31 - Barky Boats.mkv',
          ['--input', f'{src_dir}',
           '--title', '4',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e32 - Burger Shop.mkv',
          ['--input', f'{src_dir}',
           '--title', '5',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e33 - Circus.mkv',
          ['--input', f'{src_dir}',
           '--title', '6',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e28 - Seesaw.mkv',
          ['--input', f'{src_dir}',
           '--title', '7',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e29 - Movies.mkv',
          ['--input', f'{src_dir}',
           '--title', '8',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e26 - Sleepytime.mkv',
          ['--input', f'{src_dir}',
           '--title', '9',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e30 - Library.mkv',
          ['--input', f'{src_dir}',
           '--title', '10',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e34 - Swim School.mkv',
          ['--input', f'{src_dir}',
           '--title', '11',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e35 - Café.mkv',
          ['--input', f'{src_dir}',
           '--title', '12',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e36 - Postman.mkv',
          ['--input', f'{src_dir}',
           '--title', '13',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e37 - The Quiet Game.mkv',
          ['--input', f'{src_dir}',
           '--title', '14',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e38 - Mr Monkeyjocks.mkv',
          ['--input', f'{src_dir}',
           '--title', '15',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e39 - Double Babysitter.mkv',
          ['--input', f'{src_dir}',
           '--title', '16',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e40 - Bad Mood.mkv',
          ['--input', f'{src_dir}',
           '--title', '17',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e41 - Octopus.mkv',
          ['--input', f'{src_dir}',
           '--title', '18',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e42 - Bin Night.mkv',
          ['--input', f'{src_dir}',
           '--title', '19',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e43 - Muffin Cone.mkv',
          ['--input', f'{src_dir}',
           '--title', '20',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e44 - Duck Cake.mkv',
          ['--input', f'{src_dir}',
           '--title', '21',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e45 - Handstand.mkv',
          ['--input', f'{src_dir}',
           '--title', '22',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e46 - Road Trip.mkv',
          ['--input', f'{src_dir}',
           '--title', '23',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e47 - Ice Cream.mkv',
          ['--input', f'{src_dir}',
           '--title', '24',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e48 - Dunny.mkv',
          ['--input', f'{src_dir}',
           '--title', '25',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e49 - Typewriter.mkv',
          ['--input', f'{src_dir}',
           '--title', '26',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e50 - Baby Race.mkv',
          ['--input', f'{src_dir}',
           '--title', '27',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e27 - Grandad.mkv',
          ['--input', f'{src_dir}',
           '--title', '28',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/extras/Pea Pod Sausages.mkv',
          ['--input', f'{src_dir}',
           '--title', '29',
           '--audio', '1',
           '--aname', 'English',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/extras/Tea Party.mkv',
          ['--input', f'{src_dir}',
           '--title', '30',
           '--audio', '1',
           '--aname', 'English',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/extras/Old MacDonald.mkv',
          ['--input', f'{src_dir}',
           '--title', '31',
           '--audio', '1',
           '--aname', 'English',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e51 - Christman Swim.mkv',
          ['--input', f'{src_dir}',
           '--title', '32',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/s2e52 - Easter.mkv',
          ['--input', f'{src_dir}',
           '--title', '33',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/extras/Mower.mkv',
          ['--input', f'{src_dir}',
           '--title', '34',
           '--audio', '1',
           '--aname', 'English',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/extras/Flying Saucer.mkv',
          ['--input', f'{src_dir}',
           '--title', '35',
           '--audio', '1',
           '--aname', 'English',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/extras/Jingle Bells.mkv',
          ['--input', f'{src_dir}',
           '--title', '36',
           '--audio', '1',
           '--aname', 'English',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 2/extras/Make Mum Laugh.mkv',
          ['--input', f'{src_dir}',
           '--title', '37',
           '--audio', '1',
           '--aname', 'English',
           '--subtitle', '1',
           '--subname', 'English'])

os.makedirs(f'{work_dir}/Season 3', exist_ok=True)
os.makedirs(f'{work_dir}/Season 3/extras', exist_ok=True)
src_dir = src_dirs[4]
# 1: all episodes
# 2: FBI warning
transcode(f'{work_dir}/Season 3/s3e06 - Born Yesterday.mkv',
          ['--input', f'{src_dir}',
           '--title', '4',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e07 - Mini Bluey.mkv',
          ['--input', f'{src_dir}',
           '--title', '5',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e08 - Unicorse.mkv',
          ['--input', f'{src_dir}',
           '--title', '6',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e03 - Obstacle Course.mkv',
          ['--input', f'{src_dir}',
           '--title', '7',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e04 - Promises.mkv',
          ['--input', f'{src_dir}',
           '--title', '8',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e02 - Bedroom.mkv',
          ['--input', f'{src_dir}',
           '--title', '9',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e05 - Omelette.mkv',
          ['--input', f'{src_dir}',
           '--title', '10',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e09 - Curry Quest.mkv',
          ['--input', f'{src_dir}',
           '--title', '11',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e10 - Magic.mkv',
          ['--input', f'{src_dir}',
           '--title', '12',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e11 - Chest.mkv',
          ['--input', f'{src_dir}',
           '--title', '13',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e12 - Sheepdog.mkv',
          ['--input', f'{src_dir}',
           '--title', '14',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e13 - Housework.mkv',
          ['--input', f'{src_dir}',
           '--title', '15',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e14 - Pass the Parcel.mkv',
          ['--input', f'{src_dir}',
           '--title', '16',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e01 - Perfect.mkv',
          ['--input', f'{src_dir}',
           '--title', '17',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e15 - Explorers.mkv',
          ['--input', f'{src_dir}',
           '--title', '18',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e16 - Phones.mkv',
          ['--input', f'{src_dir}',
           '--title', '19',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e17 - Pavlova.mkv',
          ['--input', f'{src_dir}',
           '--title', '20',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e18 - Rain.mkv',
          ['--input', f'{src_dir}',
           '--title', '21',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e19 - Pizza Girls.mkv',
          ['--input', f'{src_dir}',
           '--title', '22',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e20 - Driving.mkv',
          ['--input', f'{src_dir}',
           '--title', '23',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e21 - Tina.mkv',
          ['--input', f'{src_dir}',
           '--title', '24',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e22 - Whale Watching.mkv',
          ['--input', f'{src_dir}',
           '--title', '25',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e23 - Family Meeting.mkv',
          ['--input', f'{src_dir}',
           '--title', '26',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e24 - Faceytalk.mkv',
          ['--input', f'{src_dir}',
           '--title', '27',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e25 - Ragdoll.mkv',
          ['--input', f'{src_dir}',
           '--title', '28',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e26 - Fairytale.mkv',
          ['--input', f'{src_dir}',
           '--title', '29',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
# 30: same as title 5
# 31: all episodes

src_dir = src_dirs[5]
# 1: all episodes
# 2: FBI warning
transcode(f'{work_dir}/Season 3/s3e31 - Onesies.mkv',
          ['--input', f'{src_dir}',
           '--title', '4',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e32 - Tradies.mkv',
          ['--input', f'{src_dir}',
           '--title', '5',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e33 - Granny Mobile.mkv',
          ['--input', f'{src_dir}',
           '--title', '6',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e28 - Stories.mkv',
          ['--input', f'{src_dir}',
           '--title', '7',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e29 - Puppets.mkv',
          ['--input', f'{src_dir}',
           '--title', '8',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e27 - Musical Statues.mkv',
          ['--input', f'{src_dir}',
           '--title', '9',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e30 - Turtleboy.mkv',
          ['--input', f'{src_dir}',
           '--title', '10',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e34 - Space.mkv',
          ['--input', f'{src_dir}',
           '--title', '11',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e35 - Smoochy Kiss.mkv',
          ['--input', f'{src_dir}',
           '--title', '12',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e36 - Dirt.mkv',
          ['--input', f'{src_dir}',
           '--title', '13',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e37 - The Decider.mkv',
          ['--input', f'{src_dir}',
           '--title', '14',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e38 - Cubby.mkv',
          ['--input', f'{src_dir}',
           '--title', '15',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e39 - Exercise.mkv',
          ['--input', f'{src_dir}',
           '--title', '16',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e40 - Relax.mkv',
          ['--input', f'{src_dir}',
           '--title', '17',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e41 - Stickbird.mkv',
          ['--input', f'{src_dir}',
           '--title', '18',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e42 - Show and Tell.mkv',
          ['--input', f'{src_dir}',
           '--title', '19',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e43 - Dragon.mkv',
          ['--input', f'{src_dir}',
           '--title', '20',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e44 - Wild Girls.mkv',
          ['--input', f'{src_dir}',
           '--title', '21',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e45 - TV Shop.mkv',
          ['--input', f'{src_dir}',
           '--title', '22',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e46 - Slide.mkv',
          ['--input', f'{src_dir}',
           '--title', '23',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e47 - Cricket.mkv',
          ['--input', f'{src_dir}',
           '--title', '24',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e48 - Ghostbasket.mkv',
          ['--input', f'{src_dir}',
           '--title', '25',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e49 - The Sign.mkv',
          ['--input', f'{src_dir}',
           '--title', '26',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
transcode(f'{work_dir}/Season 3/s3e50 - Surprise!.mkv',
          ['--input', f'{src_dir}',
           '--title', '27',
           '--audio', '2,4',
           '--aname', 'English,French',
           '--subtitle', '1',
           '--subname', 'English'])
# 28: title 16 but missing intro
# 29: all episodes
